// Generated by SandPiper(TM) 1.14-2022/10/10-beta-Pro from Redwood EDA, LLC.
// (Installed here: /home/web/live-sandhosts/mono-v154/sandpiper/distro.)
// Redwood EDA, LLC does not claim intellectual property rights to this file and provides no warranty regarding its correctness or quality.


// For silencing unused signal messages.
`define BOGUS_USE(ignore)


genvar csr, imem, xreg;


//
// Signals declared top-level.
//

// For $br_tgt_pc.
logic [31:0] L0_br_tgt_pc_a0;

// For $byte_offset.
logic [1:0] L0_byte_offset_a0;

// For $commit.
logic L0_commit_a0,
      L0_commit_a1;

// For $csr_addr.
logic [4:0] L0_csr_addr_a0;

// For $csr_new_value.
logic [31:0] L0_csr_new_value_a0;

// For $csr_old_value.
logic [31:0] L0_csr_old_value_a0;

// For $csr_operand.
logic [31:0] L0_csr_operand_a0;

// For $csr_wr_en.
logic L0_csr_wr_en_a0;

// For $d_addr.
logic [24:0] L0_d_addr_a0;

// For $d_req.
logic L0_d_req_a0;

// For $d_wdata.
logic [31:0] L0_d_wdata_a0;

// For $d_we.
logic L0_d_we_a0;

// For $d_wstrb.
logic [3:0] L0_d_wstrb_a0;

// For $dec_bits.
logic [10:0] L0_dec_bits_a0;

// For $funct3.
logic [2:0] L0_funct3_a0;

// For $funct3_valid.
logic L0_funct3_valid_a0;

// For $i_addr.
logic [23:0] L0_i_addr_a0;

// For $i_req.
logic L0_i_req_a0;

// For $imm.
logic [31:0] L0_imm_a0;

// For $imm_valid.
logic L0_imm_valid_a0;

// For $instr.
logic [31:0] L0_instr_a0,
             L0_instr_a1;

// For $is_add.
logic L0_is_add_a0;

// For $is_addi.
logic L0_is_addi_a0;

// For $is_and.
logic L0_is_and_a0;

// For $is_andi.
logic L0_is_andi_a0;

// For $is_auipc.
logic L0_is_auipc_a0;

// For $is_b_instr.
logic L0_is_b_instr_a0;

// For $is_beq.
logic L0_is_beq_a0;

// For $is_bge.
logic L0_is_bge_a0;

// For $is_bgeu.
logic L0_is_bgeu_a0;

// For $is_blt.
logic L0_is_blt_a0;

// For $is_bltu.
logic L0_is_bltu_a0;

// For $is_bne.
logic L0_is_bne_a0;

// For $is_csr.
logic L0_is_csr_a0;

// For $is_csrrc.
logic L0_is_csrrc_a0;

// For $is_csrrci.
logic L0_is_csrrci_a0;

// For $is_csrrs.
logic L0_is_csrrs_a0;

// For $is_csrrsi.
logic L0_is_csrrsi_a0;

// For $is_csrrw.
logic L0_is_csrrw_a0;

// For $is_csrrwi.
logic L0_is_csrrwi_a0;

// For $is_ebreak.
logic L0_is_ebreak_a0;

// For $is_ecall.
logic L0_is_ecall_a0;

// For $is_fence.
logic L0_is_fence_a0;

// For $is_i_instr.
logic L0_is_i_instr_a0;

// For $is_j_instr.
logic L0_is_j_instr_a0;

// For $is_jal.
logic L0_is_jal_a0;

// For $is_jalr.
logic L0_is_jalr_a0;

// For $is_lb.
logic L0_is_lb_a0;

// For $is_lbu.
logic L0_is_lbu_a0;

// For $is_lh.
logic L0_is_lh_a0;

// For $is_lhu.
logic L0_is_lhu_a0;

// For $is_load.
logic L0_is_load_a0;

// For $is_lui.
logic L0_is_lui_a0;

// For $is_lw.
logic L0_is_lw_a0;

// For $is_mem_op.
logic L0_is_mem_op_a0;

// For $is_or.
logic L0_is_or_a0;

// For $is_ori.
logic L0_is_ori_a0;

// For $is_r_instr.
logic L0_is_r_instr_a0;

// For $is_s_instr.
logic L0_is_s_instr_a0;

// For $is_sb.
logic L0_is_sb_a0;

// For $is_sh.
logic L0_is_sh_a0;

// For $is_sll.
logic L0_is_sll_a0;

// For $is_slli.
logic L0_is_slli_a0;

// For $is_slt.
logic L0_is_slt_a0;

// For $is_slti.
logic L0_is_slti_a0;

// For $is_sltiu.
logic L0_is_sltiu_a0;

// For $is_sltu.
logic L0_is_sltu_a0;

// For $is_sra.
logic L0_is_sra_a0;

// For $is_srai.
logic L0_is_srai_a0;

// For $is_srl.
logic L0_is_srl_a0;

// For $is_srli.
logic L0_is_srli_a0;

// For $is_store.
logic L0_is_store_a0;

// For $is_sub.
logic L0_is_sub_a0;

// For $is_sw.
logic L0_is_sw_a0;

// For $is_system.
logic L0_is_system_a0;

// For $is_trap.
logic L0_is_trap_a0;

// For $is_u_instr.
logic L0_is_u_instr_a0;

// For $is_xor.
logic L0_is_xor_a0;

// For $is_xori.
logic L0_is_xori_a0;

// For $jalr_tgt_pc.
logic [31:0] L0_jalr_tgt_pc_a0;

// For $ld_st_addr.
logic [31:0] L0_ld_st_addr_a0;

// For $next_pc.
logic [31:0] L0_next_pc_a0,
             L0_next_pc_a1;

// For $next_state.
logic [3:0] L0_next_state_a0,
            L0_next_state_a1;

// For $opcode.
logic [6:0] L0_opcode_a0;

// For $passed_cond.
logic L0_passed_cond_a0,
      L0_passed_cond_a1,
      L0_passed_cond_a2;

// For $pc.
logic [31:0] L0_pc_a0,
             L0_pc_a1;

// For $peri_sel.
logic [1:0] L0_peri_sel_a0;

// For $rd.
logic [4:0] L0_rd_a0;

// For $rd_valid.
logic L0_rd_valid_a0;

// For $reg_addr.
logic [1:0] L0_reg_addr_a0;

// For $reg_re.
logic L0_reg_re_a0;

// For $reg_wdata.
logic [31:0] L0_reg_wdata_a0;

// For $reg_we.
logic L0_reg_we_a0;

// For $reset.
logic L0_reset_a0,
      L0_reset_a1;

// For $result.
logic [31:0] L0_result_a0;

// For $rf1_rd_en1.
logic L0_rf1_rd_en1_a0;

// For $rf1_rd_en2.
logic L0_rf1_rd_en2_a0;

// For $rf1_rd_index1.
logic [$clog2(32)-1:0] L0_rf1_rd_index1_a0;

// For $rf1_rd_index2.
logic [$clog2(32)-1:0] L0_rf1_rd_index2_a0;

// For $rf1_wr_data.
logic [32-1:0] L0_rf1_wr_data_a0;

// For $rf1_wr_en.
logic L0_rf1_wr_en_a0;

// For $rf1_wr_index.
logic [$clog2(32)-1:0] L0_rf1_wr_index_a0;

// For $rs1.
logic [4:0] L0_rs1_a0;

// For $rs1_valid.
logic L0_rs1_valid_a0;

// For $rs2.
logic [4:0] L0_rs2_a0;

// For $rs2_valid.
logic L0_rs2_valid_a0;

// For $src1_value.
logic [32-1:0] L0_src1_value_a0;

// For $src2_value.
logic [32-1:0] L0_src2_value_a0;

// For $start.
logic L0_start_a0;

// For $state.
logic [3:0] L0_state_a0;

// For $taken_br.
logic L0_taken_br_a0;

// For $wr_data.
logic [31:0] L0_wr_data_a0;

// For $wr_en.
logic L0_wr_en_a0;

// For $wr_index.
logic [4:0] L0_wr_index_a0;

// For /csr$value.
logic [31:0] Csr_value_n1 [31:0],
             Csr_value_a0 [31:0];

// For /xreg$value.
logic [32-1:0] Xreg_value_n1 [31:0],
               Xreg_value_a0 [31:0];



   // Staging of $commit.
   always_ff @(posedge clk) L0_commit_a1 <= L0_commit_a0;

   // Staging of $instr.
   always_ff @(posedge clk) L0_instr_a1[31:0] <= L0_instr_a0[31:0];

   // Staging of $next_pc.
   always_ff @(posedge clk) L0_next_pc_a1[31:0] <= L0_next_pc_a0[31:0];

   // Staging of $next_state.
   always_ff @(posedge clk) L0_next_state_a1[3:0] <= L0_next_state_a0[3:0];

   // Staging of $passed_cond.
   always_ff @(posedge clk) L0_passed_cond_a1 <= L0_passed_cond_a0;
   always_ff @(posedge clk) L0_passed_cond_a2 <= L0_passed_cond_a1;

   // Staging of $pc.
   always_ff @(posedge clk) L0_pc_a1[31:0] <= L0_pc_a0[31:0];

   // Staging of $reset.
   always_ff @(posedge clk) L0_reset_a1 <= L0_reset_a0;


   //
   // Scope: /csr[31:0]
   //
   for (csr = 0; csr <= 31; csr++) begin : L1gen_Csr
      // Staging of $value.
      always_ff @(posedge clk) Csr_value_a0[csr][31:0] <= Csr_value_n1[csr][31:0];

   end

   //
   // Scope: /xreg[31:0]
   //
   for (xreg = 0; xreg <= 31; xreg++) begin : L1gen_Xreg
      // Staging of $value.
      always_ff @(posedge clk) Xreg_value_a0[xreg][32-1:0] <= Xreg_value_n1[xreg][32-1:0];

   end




//
// Debug Signals
//

   if (1) begin : DEBUG_SIGS

      logic [31:0] \@0$br_tgt_pc ;
      assign \@0$br_tgt_pc = L0_br_tgt_pc_a0;
      logic [1:0] \@0$byte_offset ;
      assign \@0$byte_offset = L0_byte_offset_a0;
      logic  \@0$commit ;
      assign \@0$commit = L0_commit_a0;
      logic [4:0] \@0$csr_addr ;
      assign \@0$csr_addr = L0_csr_addr_a0;
      logic [31:0] \@0$csr_new_value ;
      assign \@0$csr_new_value = L0_csr_new_value_a0;
      logic [31:0] \@0$csr_old_value ;
      assign \@0$csr_old_value = L0_csr_old_value_a0;
      logic [31:0] \@0$csr_operand ;
      assign \@0$csr_operand = L0_csr_operand_a0;
      logic  \@0$csr_wr_en ;
      assign \@0$csr_wr_en = L0_csr_wr_en_a0;
      logic [24:0] \@0$d_addr ;
      assign \@0$d_addr = L0_d_addr_a0;
      logic  \@0$d_req ;
      assign \@0$d_req = L0_d_req_a0;
      logic [31:0] \@0$d_wdata ;
      assign \@0$d_wdata = L0_d_wdata_a0;
      logic  \@0$d_we ;
      assign \@0$d_we = L0_d_we_a0;
      logic [3:0] \@0$d_wstrb ;
      assign \@0$d_wstrb = L0_d_wstrb_a0;
      logic [10:0] \@0$dec_bits ;
      assign \@0$dec_bits = L0_dec_bits_a0;
      logic [2:0] \@0$funct3 ;
      assign \@0$funct3 = L0_funct3_a0;
      logic  \@0$funct3_valid ;
      assign \@0$funct3_valid = L0_funct3_valid_a0;
      logic [23:0] \@0$i_addr ;
      assign \@0$i_addr = L0_i_addr_a0;
      logic  \@0$i_req ;
      assign \@0$i_req = L0_i_req_a0;
      logic [31:0] \@0$imm ;
      assign \@0$imm = L0_imm_a0;
      logic  \@0$imm_valid ;
      assign \@0$imm_valid = L0_imm_valid_a0;
      logic [31:0] \@0$instr ;
      assign \@0$instr = L0_instr_a0;
      logic  \@0$is_add ;
      assign \@0$is_add = L0_is_add_a0;
      logic  \@0$is_addi ;
      assign \@0$is_addi = L0_is_addi_a0;
      logic  \@0$is_and ;
      assign \@0$is_and = L0_is_and_a0;
      logic  \@0$is_andi ;
      assign \@0$is_andi = L0_is_andi_a0;
      logic  \@0$is_auipc ;
      assign \@0$is_auipc = L0_is_auipc_a0;
      logic  \@0$is_b_instr ;
      assign \@0$is_b_instr = L0_is_b_instr_a0;
      logic  \@0$is_beq ;
      assign \@0$is_beq = L0_is_beq_a0;
      logic  \@0$is_bge ;
      assign \@0$is_bge = L0_is_bge_a0;
      logic  \@0$is_bgeu ;
      assign \@0$is_bgeu = L0_is_bgeu_a0;
      logic  \@0$is_blt ;
      assign \@0$is_blt = L0_is_blt_a0;
      logic  \@0$is_bltu ;
      assign \@0$is_bltu = L0_is_bltu_a0;
      logic  \@0$is_bne ;
      assign \@0$is_bne = L0_is_bne_a0;
      logic  \@0$is_csr ;
      assign \@0$is_csr = L0_is_csr_a0;
      logic  \@0$is_csrrc ;
      assign \@0$is_csrrc = L0_is_csrrc_a0;
      logic  \@0$is_csrrci ;
      assign \@0$is_csrrci = L0_is_csrrci_a0;
      logic  \@0$is_csrrs ;
      assign \@0$is_csrrs = L0_is_csrrs_a0;
      logic  \@0$is_csrrsi ;
      assign \@0$is_csrrsi = L0_is_csrrsi_a0;
      logic  \@0$is_csrrw ;
      assign \@0$is_csrrw = L0_is_csrrw_a0;
      logic  \@0$is_csrrwi ;
      assign \@0$is_csrrwi = L0_is_csrrwi_a0;
      logic  \@0$is_ebreak ;
      assign \@0$is_ebreak = L0_is_ebreak_a0;
      logic  \@0$is_ecall ;
      assign \@0$is_ecall = L0_is_ecall_a0;
      logic  \@0$is_fence ;
      assign \@0$is_fence = L0_is_fence_a0;
      logic  \@0$is_i_instr ;
      assign \@0$is_i_instr = L0_is_i_instr_a0;
      logic  \@0$is_j_instr ;
      assign \@0$is_j_instr = L0_is_j_instr_a0;
      logic  \@0$is_jal ;
      assign \@0$is_jal = L0_is_jal_a0;
      logic  \@0$is_jalr ;
      assign \@0$is_jalr = L0_is_jalr_a0;
      logic  \@0$is_lb ;
      assign \@0$is_lb = L0_is_lb_a0;
      logic  \@0$is_lbu ;
      assign \@0$is_lbu = L0_is_lbu_a0;
      logic  \@0$is_lh ;
      assign \@0$is_lh = L0_is_lh_a0;
      logic  \@0$is_lhu ;
      assign \@0$is_lhu = L0_is_lhu_a0;
      logic  \@0$is_load ;
      assign \@0$is_load = L0_is_load_a0;
      logic  \@0$is_lui ;
      assign \@0$is_lui = L0_is_lui_a0;
      logic  \@0$is_lw ;
      assign \@0$is_lw = L0_is_lw_a0;
      logic  \@0$is_mem_op ;
      assign \@0$is_mem_op = L0_is_mem_op_a0;
      logic  \@0$is_or ;
      assign \@0$is_or = L0_is_or_a0;
      logic  \@0$is_ori ;
      assign \@0$is_ori = L0_is_ori_a0;
      logic  \@0$is_r_instr ;
      assign \@0$is_r_instr = L0_is_r_instr_a0;
      logic  \@0$is_s_instr ;
      assign \@0$is_s_instr = L0_is_s_instr_a0;
      logic  \@0$is_sb ;
      assign \@0$is_sb = L0_is_sb_a0;
      logic  \@0$is_sh ;
      assign \@0$is_sh = L0_is_sh_a0;
      logic  \@0$is_sll ;
      assign \@0$is_sll = L0_is_sll_a0;
      logic  \@0$is_slli ;
      assign \@0$is_slli = L0_is_slli_a0;
      logic  \@0$is_slt ;
      assign \@0$is_slt = L0_is_slt_a0;
      logic  \@0$is_slti ;
      assign \@0$is_slti = L0_is_slti_a0;
      logic  \@0$is_sltiu ;
      assign \@0$is_sltiu = L0_is_sltiu_a0;
      logic  \@0$is_sltu ;
      assign \@0$is_sltu = L0_is_sltu_a0;
      logic  \@0$is_sra ;
      assign \@0$is_sra = L0_is_sra_a0;
      logic  \@0$is_srai ;
      assign \@0$is_srai = L0_is_srai_a0;
      logic  \@0$is_srl ;
      assign \@0$is_srl = L0_is_srl_a0;
      logic  \@0$is_srli ;
      assign \@0$is_srli = L0_is_srli_a0;
      logic  \@0$is_store ;
      assign \@0$is_store = L0_is_store_a0;
      logic  \@0$is_sub ;
      assign \@0$is_sub = L0_is_sub_a0;
      logic  \@0$is_sw ;
      assign \@0$is_sw = L0_is_sw_a0;
      logic  \@0$is_system ;
      assign \@0$is_system = L0_is_system_a0;
      logic  \@0$is_trap ;
      assign \@0$is_trap = L0_is_trap_a0;
      logic  \@0$is_u_instr ;
      assign \@0$is_u_instr = L0_is_u_instr_a0;
      logic  \@0$is_xor ;
      assign \@0$is_xor = L0_is_xor_a0;
      logic  \@0$is_xori ;
      assign \@0$is_xori = L0_is_xori_a0;
      logic [31:0] \@0$jalr_tgt_pc ;
      assign \@0$jalr_tgt_pc = L0_jalr_tgt_pc_a0;
      logic [31:0] \@0$ld_st_addr ;
      assign \@0$ld_st_addr = L0_ld_st_addr_a0;
      logic [31:0] \@0$next_pc ;
      assign \@0$next_pc = L0_next_pc_a0;
      logic [3:0] \@0$next_state ;
      assign \@0$next_state = L0_next_state_a0;
      logic [6:0] \@0$opcode ;
      assign \@0$opcode = L0_opcode_a0;
      logic  \@0$passed_cond ;
      assign \@0$passed_cond = L0_passed_cond_a0;
      logic [31:0] \@0$pc ;
      assign \@0$pc = L0_pc_a0;
      logic [1:0] \@0$peri_sel ;
      assign \@0$peri_sel = L0_peri_sel_a0;
      logic [4:0] \@0$rd ;
      assign \@0$rd = L0_rd_a0;
      logic  \@0$rd_valid ;
      assign \@0$rd_valid = L0_rd_valid_a0;
      logic [1:0] \@0$reg_addr ;
      assign \@0$reg_addr = L0_reg_addr_a0;
      logic  \@0$reg_re ;
      assign \@0$reg_re = L0_reg_re_a0;
      logic [31:0] \@0$reg_wdata ;
      assign \@0$reg_wdata = L0_reg_wdata_a0;
      logic  \@0$reg_we ;
      assign \@0$reg_we = L0_reg_we_a0;
      logic  \@0$reset ;
      assign \@0$reset = L0_reset_a0;
      logic [31:0] \@0$result ;
      assign \@0$result = L0_result_a0;
      logic  \@0$rf1_rd_en1 ;
      assign \@0$rf1_rd_en1 = L0_rf1_rd_en1_a0;
      logic  \@0$rf1_rd_en2 ;
      assign \@0$rf1_rd_en2 = L0_rf1_rd_en2_a0;
      logic [$clog2(32)-1:0] \@0$rf1_rd_index1 ;
      assign \@0$rf1_rd_index1 = L0_rf1_rd_index1_a0;
      logic [$clog2(32)-1:0] \@0$rf1_rd_index2 ;
      assign \@0$rf1_rd_index2 = L0_rf1_rd_index2_a0;
      logic [32-1:0] \@0$rf1_wr_data ;
      assign \@0$rf1_wr_data = L0_rf1_wr_data_a0;
      logic  \@0$rf1_wr_en ;
      assign \@0$rf1_wr_en = L0_rf1_wr_en_a0;
      logic [$clog2(32)-1:0] \@0$rf1_wr_index ;
      assign \@0$rf1_wr_index = L0_rf1_wr_index_a0;
      logic [4:0] \@0$rs1 ;
      assign \@0$rs1 = L0_rs1_a0;
      logic  \@0$rs1_valid ;
      assign \@0$rs1_valid = L0_rs1_valid_a0;
      logic [4:0] \@0$rs2 ;
      assign \@0$rs2 = L0_rs2_a0;
      logic  \@0$rs2_valid ;
      assign \@0$rs2_valid = L0_rs2_valid_a0;
      logic [32-1:0] \@0$src1_value ;
      assign \@0$src1_value = L0_src1_value_a0;
      logic [32-1:0] \@0$src2_value ;
      assign \@0$src2_value = L0_src2_value_a0;
      logic  \@0$start ;
      assign \@0$start = L0_start_a0;
      logic [3:0] \@0$state ;
      assign \@0$state = L0_state_a0;
      logic  \@0$taken_br ;
      assign \@0$taken_br = L0_taken_br_a0;
      logic [31:0] \@0$wr_data ;
      assign \@0$wr_data = L0_wr_data_a0;
      logic  \@0$wr_en ;
      assign \@0$wr_en = L0_wr_en_a0;
      logic [4:0] \@0$wr_index ;
      assign \@0$wr_index = L0_wr_index_a0;

      //
      // Scope: /csr[31:0]
      //
      for (csr = 0; csr <= 31; csr++) begin : \/csr 
         logic  \/@0$csr_wr ;
         assign \/@0$csr_wr = L1_Csr[csr].L1_csr_wr_a0;
         logic [31:0] \/@-1$value ;
         assign \/@-1$value = Csr_value_n1[csr];
      end

      //
      // Scope: /xreg[31:0]
      //
      for (xreg = 0; xreg <= 31; xreg++) begin : \/xreg 
         logic [32-1:0] \/@-1$value ;
         assign \/@-1$value = Xreg_value_n1[xreg];
         logic  \/@0$wr ;
         assign \/@0$wr = L1_Xreg[xreg].L1_wr_a0;
      end


   end

